chat:
  join:
    prefix: "&aJoin"
    message: "&5&l{player} &7has joined the game."
  leave:
    prefix: "&4Leave"
    message: "&5&l{player} &7has left the game."
scoreboard:
  title: "&5&lMytheral &fNetwork"
  contents:
    before:
      - "&7&m-------------------------------"
    after:
      - "&7&m-------------------------------"
      - "&fplay.mytheral.net"
    states:
      lobby:
        - "&7Waiting for players..."
        - ""
        - "&f&lPlayers: &5{current}&7/&f{total}"
        - ""
        - "&f&lKit: &5{kit}"
        - "&f&lJewels: &5{balance}"