Database:
  Uri: "mongodb+srv://Aura6:CUrlito11@cluster0.spwav.mongodb.net/?retryWrites=true&w=majority"
  Database: SuperSmashLegendsRevamped
  Collection: Players
  Enabled: true
Rules:
  - "&7Welcome to &5&lSuper Smash Legends!"
  - "&cAttack &7others to achieve victory."
  - "&7But die &c{LIVES} &7times, and you're out!"
  - "&7Use &dabilities &7through your hotbar."
  - "&7The game is starting soon. &a&lGood Luck!"
Description:
  - "&5&l------------------------------"
  - "&7Welcome to &5&o&lSuper Smash Legends!"
  - ""
  - "&7&cFight &7and &ckill &7other players."
  - "&7Toggle flight to &bdouble jump&7."
  - "&7Click in your hotbar to use &dabilities&7."
  - ""
  - "&2&lArena - {ARENA} &7by &f&l{AUTHORS}"
  - "&5&l------------------------------"
KitHologramHeight: 2.7
Death:
  Skin: "BroliaiJagm"
  Velocity: 0.35
  Duration: 80
LeaderboardSizes:
  Wins: 10
  Kills: 10
Economy:
  StartingJewels: 100000
  OfflineJewels: 50000
  JewelsEarnedWeights:
    PerKill: 50
    WinBonus: 250
Collision:
  CheckRange: 2
  CheckStep: 0.2
  FaceAccuracy: 0.05
  MaxStuckDuration: 10
Game:
  Lives: 4
  Team:
    Size: 1
    Count: 4
  Tutorial:
    DurationTicks: 200
    DelayTicks: 45
  DeathWaitSeconds: 5
  StartWaitSeconds: 5
  EndWaitSeconds: 5
  AllowKitSelectionInGame: false
Damage:
  DefaultImmunityTicks: 10
  Lifetime: 240
  Indicator:
    ComboDuration: 70
    Height:
      Entity: 0.7
      Player: 1.5
  Melee:
    Kb: 0.9
    KbY: 0.45
    FactorsKb: false
    FactorsHealth: false
  KbHealthMultiplier:
    Min: 1
    Max: 2
Power:
  Frequency: 1500
  Height: 100
  DropSpeed: 0.5
  DetectionRadiusSquared: 4.5
  Powers:
    Droid:
      Name: "&8Droid"
      Item:
        Material: IRON_BLOCK
      Description:
        - "&7Command a legion of fast, hungry droids."
        - "&7With an advanced, built-in homing system,"
        - "&7they're able to hunt down prey at an "
        - "&7unparalleled success rate."
      Rarity: 10
      Uses: 3
      Side:
        HitBox: 0
        Block:
          Material: IRON_FENCE
      Main:
        Speed: 0.75
        HomingSpeed: 1.75
        Vision: 30
        Damage: 8
        ImmunityTicks: 0
        Kb: 2.75
        KbY: 1
        HitBox: 2
        HasGravity: false
        Block:
          Material: IRON_BLOCK
