Database:
  Uri: "mongodb+srv://Me:CUrlito11@supersmashcluster.bwts5hj.mongodb.net/?retryWrites=true&w=majority"
  Database: SuperSmash
  Collection: Players
  Enabled: true
Rules:
  - "&7Welcome to &5&lSuper Smash Legends!"
  - "&cAttack &7others to achieve victory."
  - "&7But die &c{LIVES} &7times, and you're out!"
  - "&7Use &dabilities &7through your hotbar."
  - "&7The game is starting soon. &a&lGood Luck!"
Description:
  - "&5&l------------------------------"
  - "&7Welcome to &5&o&lSuper Smash Legends!"
  - ""
  - "&7&cFight &7and &ckill &7other players."
  - "&7Toggle flight to &bdouble jump&7."
  - "&7Click in your hotbar to use &dabilities&7."
  - ""
  - "&2&lArena - {ARENA} &7by &f&l{AUTHORS}"
  - "&5&l------------------------------"
KitHologramHeight: 2.7
Death:
  Velocity: 0.3
  Duration: 70
LeaderboardSizes:
  Wins: 10
  Kills: 10
Collision:
  CheckRange: 2
  CheckStep: 0.2
  FaceAccuracy: 0.1
  MaxStuckDuration: 10
Game:
  Lives: 4
  Team:
    Size: 1
    Count: 4
  Tutorial:
    DurationTicks: 200
    DelayTicks: 55
  LobbyCountdown:
    Seconds: 30
    NotifyInterval: 10
  MaxGameSeconds: 720
  DeathWaitSeconds: 3
  StartWaitSeconds: 5
  EndWaitSeconds: 5
  AllowKitSelectionInGame: true
Damage:
  DefaultImmunityTicks: 10
  Lifetime: 240
  Indicator:
    ComboDuration: 80
    Height:
      Entity: 0.7
      Player: 1.5
  Melee:
    Kb: 0.9
    KbY: 0.45
    FactorsKb: false
    FactorsHealth: false
  KbHealthMultiplier:
    Min: 1
    Max: 2
