name: SuperSmashLegends
version: 1.0-SNAPSHOT
main: io.github.aura6.supersmashlegends.SuperSmashLegends
authors: [ Aura6 ]
api-version: 1.8.8
depend: [ ProtocolLib ]

commands:
  kit:
    description: Opens the kit GUI or sets a player's kit.
  reloadconfig:
    description: Dynamically reloads the plugin configuration files.
    aliases: [ rc, reloadconfigs ]
  start:
    description: Forces the game to start.
  end:
    description: Forces the game to end.
  skip:
    description: Skips to the provided Game State.
  dummy:
    description: Spawns a dummy above the player.