name: SuperSmashLegends
version: 1.0.0-alpha
main: com.github.zilosz.ssl.SSL
authors: [Zilosz]
api-version: 1.8.8
softdepend:
  - TitleAPI
  - NameTagEdit
  - ActionBarAPI
  - LibsDisguises
  - HolographicDisplays
  - ProtocolLib
  - FastAsyncWorldEdit
  - Citizens

commands:
  play:
    description: Skips to the IN_GAME game state.
    usage: "/<command>"
  kit:
    description: Opens the kit GUI or sets a player's kit.
    usage: "/<command> [kit]"
  reloadconfig:
    description: Dynamically reloads configuration files.
    aliases: [rc, reloadconfigs]
    permission: op
    usage: "/<command>"
  start:
    description: Forces the game to start.
    permission: op
    usage: "/<command>"
  end:
    description: Forces the game to end.
    permission: op
    usage: "/<command>"
  skip:
    description: Skips to the provided Game State.
    permission: op
    usage: "/<command> <state>"
  dummy:
    description: Spawns a dummy above the player.
    permission: op
    usage: "/<command>"
  loc:
    description: Sends the player's location.
    permission: op
    usage: "/<command>"
  damage:
    description: Damage a player or yourself.
    usage: "/<command> <damage> [player]"
    permission: op
  spec:
    description: Toggle spectator mode for upcoming games.
    usage: "/<command>"